In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
### SENTENCES
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understanding the concept of the words',
]

In [35]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understanding the concept of the words']

In [36]:
## Define the Vocabulary Size ()
voc_size=10000

In [49]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understanding the concept of the words']

In [50]:
## One Hot Encoding Representing ()
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2024, 8865, 3187, 1177],
 [2024, 8865, 3187, 5507],
 [2024, 2527, 3187, 3821],
 [9061, 7828, 8861, 6170, 1648],
 [9061, 7828, 8861, 6170, 1165],
 [7694, 2024, 6385, 3187, 2024, 7033]]

In [39]:
## Word embedding 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences ## as we know that to train and work onn our model each sentence should have same number of words so to convert different sentences in same number of words we use this library(pad_sequence)
from tensorflow.keras.models import Sequential
import numpy as np


In [51]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2024 8865 3187 1177]
 [   0    0    0    0 2024 8865 3187 5507]
 [   0    0    0    0 2024 2527 3187 3821]
 [   0    0    0 9061 7828 8861 6170 1648]
 [   0    0    0 9061 7828 8861 6170 1165]
 [   0    0 7694 2024 6385 3187 2024 7033]]


In [52]:
# Feature Representation
dim=10

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential([
    Input(shape=(sent_length,)),     
    Embedding(voc_size, dim)
])

model.compile(optimizer="adam", loss="mse")
model.summary()


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
embedded_docs[0]

array([   0,    0,    0,    0, 2024, 8865, 3187, 1177], dtype=int32)

In [43]:
model.predict(embedded_docs) ## Since we have 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[[ 0.04919341,  0.03917268, -0.02026327,  0.04950381,
         -0.0222214 ,  0.03747152, -0.019365  , -0.01260464,
         -0.04858304, -0.02347469],
        [ 0.04919341,  0.03917268, -0.02026327,  0.04950381,
         -0.0222214 ,  0.03747152, -0.019365  , -0.01260464,
         -0.04858304, -0.02347469],
        [ 0.04919341,  0.03917268, -0.02026327,  0.04950381,
         -0.0222214 ,  0.03747152, -0.019365  , -0.01260464,
         -0.04858304, -0.02347469],
        [ 0.04919341,  0.03917268, -0.02026327,  0.04950381,
         -0.0222214 ,  0.03747152, -0.019365  , -0.01260464,
         -0.04858304, -0.02347469],
        [-0.03936457, -0.01818023, -0.00797031, -0.02867391,
          0.04039997,  0.0433966 ,  0.00473096, -0.01948977,
         -0.02028587, -0.03713278],
        [-0.00460897, -0.04037453,  0.0141881 , -0.00151686,
          0.00113272, -0.02233158,  0.01910711,  0.02576828,
          0.0428367 , -0.0108942 ],
        [ 0.01860844, -0.04195963, -0.00537697,  0.0